# Generated by Django 4.2.4 on 2023-09-17 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMSAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_management.company')),
            ],
        ),
        migrations.CreateModel(
            name='IMSInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('unit_price_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims.imsaddress')),
            ],
        ),
        migrations.CreateModel(
            name='IMSInventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(editable=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.CharField(choices=[('CKO', 'ወጪ'), ('CKI', 'ገቢ'), ('MOV', 'ዝውው'), ('RTK', 'ተጨማሪ ገቢ ተደርጓል')], default='CKO', max_length=3)),
                ('quantity', models.FloatField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ims_transaction_destination', to='ims.imsaddress')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ims.imsinventory')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ims_transaction_source', to='ims.imsaddress')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='imsinventorytransaction',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='ims_transaction_positive_float_value'),
        ),
        migrations.AlterUniqueTogether(
            name='imsinventory',
            unique_together={('name', 'sku', 'address')},
        ),
    ]
