# Generated by Django 4.2.4 on 2023-09-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imsinventorytransaction',
            name='source',
        ),
    ]
