# Generated by Django 4.2.4 on 2023-08-18 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_management.company')),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=32)),
                ('access_level', models.CharField(choices=[('SU', 'Superuser/Administrator'), ('PU', 'Power User/Manager'), ('FN', 'Functional/User Role Access'), ('RO', 'Read-Only/User'), ('DE', 'Data Entry/Transaction User'), ('EX', 'External/Supplier/Customer'), ('RE', 'Restricted Access'), ('WF', 'Workflow/Approval User'), ('RP', 'Reporting/User Analytics'), ('AD', 'Audit/User Activity')], default='RO', max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_management.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_management.departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'employee_id')},
            },
        ),
    ]
