# Generated by Django 4.2.4 on 2023-09-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hmsstocktransaction',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='positive_float_value'),
        ),
    ]
