# Generated by Django 4.2.4 on 2023-09-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_hmsstocktransaction_positive_float_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hmsstocktransaction',
            old_name='case_id',
            new_name='transaction_id',
        ),
    ]
