# Generated by Django 4.2.4 on 2023-09-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_rename_case_id_hmsstocktransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmswarehouse',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
