name: timebg_prod deploy to cPanel

on:
  push:
    branches:
      - timebg_prof

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput

    - name: Deploy to cPanel
      run: |
        ssh ${{ secrets.CPANEL_SSH_USER }}@${{ secrets.CPANEL_HOST }} "cd /path/to/your/app && git pull origin main && python manage.py migrate && python manage.py restart"
      env:
        CPANEL_SSH_USER: ${{ secrets.CPANEL_SSH_USER }}
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
      secrets:
        CPANEL_SSH_USER: ${{ secrets.CPANEL_SSH_USER }}
        CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
